### CREATE TABLE
GET http://localhost:8089/api/category/commit

### DELETE TABLE
DELETE  http://localhost:8089/api/category/drop

### GET ALL CATEGORYS
GET http://localhost:8089/api/category/
# authtoken:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdUBnbWFpbC5jb20iLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE2MTAwMzQyNDUsImV4cCI6MTYxMDAzNzg0NX0.l_eLKevrZLt08UrZ1gwCNG5cg0zAP_9pm5j8MAvlTmw

### INSERT NEW CATEGORY
POST http://localhost:8089/api/category/
Content-Type: application/json

{
    "name" : "zaki",
    "email" : "zaki@gmail.com",
    "password" : "maulana"
}

### UPDATE CATEGORY
PUT  http://localhost:8089/api/category/
Content-Type: application/json

{
    "name" : "maulana",
    "email" : "mau@gmail.com",
}

### DELETE CATEGORY
DELETE http://localhost:8089/api/category/?email=zaki@gmail.com
